<p>PLEASE READ THESE TERMS OF USE BEFORE USING MYRIGHT. </p>

<p>MyRight, Inc. ("MyRight," "we," "us" or "Company"), a Delaware corporation, hosts, maintains, and moderates www.myright.me ("Website") to serve as a convenient and focused aggregation platform of legal content. The following Terms and Conditions of Use ("Agreement") apply to your use of the Website including, but not limited to, any content, functionality, and services offered on or through the Website. </p>

<p>By accessing or using the Website, you, the user, accept and agree to be legally bound by and abide to the Agreement. </p>

<p>1. Modifications to the Terms of Use. MyRight reserves the right to change this Agreement at any time and at its sole discretion. Current and dated versions of the Agreement will appear on the Website and become effective immediately upon publication. Your continued use of the Website following such publication constitutes your acceptance and agreement to all changes to date.</p>

<p>Last Modified: August 2, 2012</p>

<p>2. Definition of Intellectual Property Rights. All patent rights; copyright rights; moral rights; rights of publicity; trademark, trade dress and service mark rights (and associated goodwill); trade secret rights; and all other intellectual property and proprietary rights as may now exist or hereafter come into existence, and all applications for any of these rights and registrations, renewals and extensions of any of these rights, in each case under the laws of any state, country, territory or other jurisdiction.</p>

<p>3. User Content.</p>

<p>a. User content. MyRight allows you to post content on the Website, including articles, photos, comments, and other materials. You retain all Intellectual Property Rights to anything that you post, display, share, publish, transmit or otherwise make available on the Website ("User Content").</p>

<p>b. How myRight and other users can use your content. You grant us a non-exclusive, royalty-free, transferable, sub-licensable, worldwide license to use, display, reproduce, re-post, re-format, re-arrange, modify, and distribute User Content on the Website for purposes of operating and providing services to you and other users. Other users may search for, see, use, edit, comment, branch and/or re-post your User Content that you make available through the Website. </p>

<p>c. How long we keep your content. We reserve the right to keep User Content on the Website for an indefinite period of time at our sole discretion. MyRight and other users may retain and continue to display, reproduce, re-post, modify, re-arrange, and distribute any of your User Content, even if you have terminated or deactivated your account. </p>

<p>d. Your responsibility for your content. </p>

<p>i. To myRight and our community. You understand and acknowledge that you are responsible for any User Content you post, submit, or contribute, and you, not the Company, have full responsibility for such content, including its legality, reliability, accuracy, and appropriateness. You agree to the Content Standards outlined below. We are not responsible, or liable to any third party, for the content or accuracy of any materials posted by you or any other user of the Website. We reserve the right, but are not obligated, to remove User Content from the Website for any reason, including User Content we believe violates this Agreement. </p>

<p>ii. To third parties. You agree that any User Content that you post to the Website does not and will not violate any law or infringe the right of any third party, including without limitation any Intellectual Property Rights, publicity rights, or rights of privacy. Furthermore, you represent and warrant that you own or control rights to post the User Content and have the right to grant the Company and its affiliates the license granted above. You represent and warrant that all of your User Content does and will comply with this Agreement, and you agree to defend, indemnify, and hold harmless the Company and its affiliates and licensors for any breach of that representation and warranty.</p>

<p>e. Content Standards. These content standards apply to any and all User Content. User Content must comply with all applicable federal, state, local and international laws and regulations. Without limiting the foregoing, User Content must not:
<ul>
<li>Contain any material which is defamatory, obscene, indecent, abusive, offensive, harassing, violent, hateful, inflammatory or otherwise objectionable.</li><li>Promote sexually explicit or pornographic material, violence, or discrimination based on race, sex, religion, nationality, disability, sexual orientation or age.</li><li>Infringe any patent, trademark, trade secret, copyright or other intellectual property rights of any other person.</li><li>Violate the legal rights (including the rights of publicity and privacy) of others or contain any material that could give rise to any civil or criminal liability under applicable laws or regulations or that otherwise may be in conflict with these Terms of Service.</li><li>Be likely to deceive any person.</li><li>Promote any illegal activity, or advocate, promote or assist any unlawful act.</li><li>Cause annoyance, inconvenience or needless anxiety or be likely to upset, embarrass, alarm or annoy any other person.</li><li>Be used to impersonate any person, or to misrepresent your identity or affiliation with any person or organization.</li><li>Involve commercial activities or sales, such as contests, sweepstakes and other sales promotions, barter or advertising.</li><li>Give the impression that they emanate from us or any other person or entity, if this is not the case.</li>
</ul>
</p>


<p>4. MyRight Content. Except for User Content, the Website itself, all content and other subject matter included on or within the Website, and all Intellectual Property Rights in or related to the Website or any such content or other subject matter ("MyRight Content") are the property of MyRight and its licensors. Nothing contained within this Agreement shall be construed as conferring any license or right, by implication, estoppels or otherwise, under copyright or other intellectual property rights. </p>

<p>5. Prohibited Uses. You may use the Website only for lawful purposes and in accordance with this Agreement. You agree not to: a. Use the Website in any way that violates any applicable federal, state, local and international law or regulation, including any laws regarding the export of data or software to and from the United States or other countries. b. Modify, reproduce, distribute, sell, license, or otherwise exploit any parts of the Website for commercial or other purposes, without permission. c. Use the Website to transmit or procure sending of any advertising or solicitation material without express permission from myRight. d. Use the Website to impersonate or attempt to impersonate myRight or a myRight employee, or another user, person or entity. e. Engage in any conduct which restricts or inhibits anyone's use or enjoyment of the Website, or which, as determined at myRight's discretion, may harm myRight or users of the Website or expose them to liability. f. Use any robot, spider or other automatic devices to monitor or copy any of the material in the Website for any purpose. g. Attempt to gain unauthorized access to, interfere with, damage or disrupt any parts of the Website. h. To send, upload, download, use or re-use any material which does not comply with the Content Standards set below.</p>

<p>6. Monitoring and Enforcement of Content. MyRight has no obligation to monitor, review, or screen any content on the Website. MyRight reserves the right to, without notice and in its sole discretion,: a. Remove or refuse to publish any User Content for any or no reason. b. Take any action with respect to any User Content myRight deems necessary or appropriate regardless of whether such content violates this Agreement. c. Disclose user identities when required to do so by applicable law, including in response to a law enforcement request supported by a valid court order.</p>

<p>7. Copyright Infringement. If you believe that any User Content violate your copyright, please email us at info@myright.me for instructions on sending us a notice of copyright infringement. It is the policy of the Company to terminate the user accounts of repeat infringers, and we are in the process of setting up a DMCA compliant process for managing cases of infringement.</p>

<p>8. No Reliance on Information within the Website. The information presented in or through the Website is made available solely for general information purposes and is insufficient to constitute legal advice or suggest any particular course of action. MyRight does not warrant any such information to be accurate, complete, up-to-date, or useful. Any reliance you place on such information is strictly at your own risk. MyRight disclaims all liability and responsibility arising from any reliance placed on such information by you, another user, or anyone who may be informed of any of the Website's contents.</p>

<p>9. Disclaimer of Warranties. The Website and content is provided on an "as is" basis. MyRight expressly disclaims all warranties, including the warranties of merchantability, fitness for a particular purpose, and non-infringement. MyRight disclaims all responsibility for any loss, injury, claim, liability, or damage of any kind resulting from, arising out of or any way related to: a. Any User Content that you or any other user or third party posts, shares, distributes, modifies, re-formats, re-arranges, or displays on the Website. b. Any errors in or omissions from the Website and its content, including but not limited to technical inaccuracies, typographical errors, and information that is outdated, inaccurate, or incomplete. c. Any third party service, content, or information therein directly or indirectly accessed through links in the Website. d. The unavailability or any access failure of the Website or any portion thereof. e. Your use of the Website. f. Any MyRight Content. g. Your use of any equipment or software in connection with the Website.</p>

<p>10. LIMITATION OF LIABILITY. </p>

<p>(a) You understand and expressly agree that myRight and its affiliates are not liable for any direct, indirect, incidental, special, consequential, or exemplary damages, even if myRight has been advised of the possibility of such damages, resulting from:  a. Any User Content that you or any other user or third party posts, shares, distributes, modifies, re-formats, re-arranges, or displays on the Website. b. The use or the inability to use the Website, even if assisted by myRight or its affiliates. c. The cost of procurement of services resulting from any information or services purchased or obtained, messages received, or transactions entered into through or from use of the Website. d. Unauthorized access to or alteration of your transmissions or data. e. Statements or conduct of any third party on the Website. f. Any other matter relating to use of the Website. </p>

<p>(b) You agree to defend, indemnify, and hold harmless myRight, its affiliates, contractors, suppliers, directors, employees, and agents harmless from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses or fees, including but not limited to reasonable attorneys' fees, resulting from your violation of this Agreement or your use of the Website, including, without limitation, any User Content or use of content, information, or services obtained from the Website other than as expressly authorized in this Agreement. </p>

<p>11. No Attorney-Client Relationship. Some of our users are attorneys ("Attorney") and they may post content on the Website. The Attorney is providing and endorsing content on the Website for information purposes only. The information is insufficient to constitute legal advice or suggest any particular course of action. The Attorney has not agreed to represent you, nor has an attorney-client relationship been formed in any other manner. Submitting personal information via the Website does not form an attorney-client relationship. No such relationship is formed until there is a mutual agreement to provide legal services outside of the use of this Website.</p>

<p>12. Third-party Links, Sites, and Services. The Website may contain links to third-party websites, a</p>

<p>13. No Endorsement of Lawyers. MyRight does not select, approve, or otherwise endorse any particular Attorney on the Website. Any and all recommendations, information, or content generated by the Attorney could be inaccurate, outdated, or incomplete, and are difficult or impossible to verify. Therefore, myRight expressly disclaims any representation or warranty that such information is correct, current, or reliable. The information contained in this Website is intended for educational purposes only and shall not be considered as legal advice. MyRight disclaims all liability and responsibility arising from any reliance placed on such information by you or any other visitor to the Website, or by anyone who may be informed of any of its contents. </p>

<p>14. Third-party Links, Sites, and Services. You acknowledge that the Website may contain links to third-party websites, advertisers, affiliates, sponsorships, services, special offers, or other events or activities that are not owned or controlled by MyRight. These third-parties are solely responsible for ensuring that material submitted for use on the Website is accurate and complies with any and all applicable laws. You agree that myRight does not assume any responsibility for any such third-pary sites, information, materials, products, or services. If you access any third party website, service, or content from the Website, you do so at your own risk and you agree that myRight will have no liability arising from your use or access to any third-party website, service, or content. </p>

<p>15. Governing Law and Jurisdiction. This Agreement and any dispute or claim arising out of, or related to them or their subject matter or formation, shall be governed by and construed in accordance with the internal laws of the State of Delaware without giving effect to any choice or conflict of law provision or rule. Any legal suit, action, or proceeding arising out of, or related to, this Agreement or the Application shall be instituted exclusively in the federal courts of the United States or the courts of the State of Delaware. All parties agree to the exclusive jurisdiction of such courts.</p>

<p>16. Termination. MyRight reserves the right, without notice and in its sole discretion, to terminate your access to and use of all or part of the Website for any or no reason, including, but not limited to, any violation of this Agreement. </p>