-- phpMyAdmin SQL Dump
-- version 3.4.10.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 25, 2012 at 12:55 PM
-- Server version: 5.0.95
-- PHP Version: 5.2.9

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `checkmyr_myright`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(2) NOT NULL auto_increment,
  `slug` varchar(20) collate latin1_general_ci NOT NULL,
  `name` varchar(60) collate latin1_general_ci NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=5 ;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `slug`, `name`) VALUES
(1, 'election2012', 'Election 2012'),
(2, 'startups', 'Startup Law'),
(3, 'tickets', 'Tickets'),
(4, 'dui', 'DUI');

-- --------------------------------------------------------

--
-- Table structure for table `comments`
--

CREATE TABLE IF NOT EXISTS `comments` (
  `id` int(20) NOT NULL auto_increment,
  `element_id` int(20) NOT NULL,
  `poster` int(10) NOT NULL,
  `comment` varchar(500) collate latin1_general_ci NOT NULL,
  `votes` int(5) NOT NULL,
  `date_created` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `links`
--

CREATE TABLE IF NOT EXISTS `links` (
  `id` int(20) NOT NULL auto_increment,
  `type` varchar(15) collate latin1_general_ci NOT NULL,
  `url` text collate latin1_general_ci NOT NULL,
  `category` int(2) NOT NULL,
  `summary` varchar(1000) collate latin1_general_ci NOT NULL,
  `title` varchar(200) collate latin1_general_ci NOT NULL,
  `votes` int(5) NOT NULL,
  `tags` varchar(200) collate latin1_general_ci NOT NULL,
  `slug` varchar(200) collate latin1_general_ci NOT NULL,
  `source` varchar(50) collate latin1_general_ci NOT NULL,
  `poster` int(10) NOT NULL,
  `date_created` int(10) NOT NULL,
  `location` varchar(50) collate latin1_general_ci NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=149 ;

--
-- Dumping data for table `links`
--

INSERT INTO `links` (`id`, `type`, `url`, `category`, `summary`, `title`, `votes`, `tags`, `slug`, `source`, `poster`, `date_created`, `location`) VALUES
(1, 'primary', 'http://www.ca1.uscourts.gov/pdf.opinions/10-2204P-01A.pdf', 1, 'DOMA is a federal law that defines marriage as the legal union between one man and one women. ', 'Opinion of Case Finding DOMA Unconstitutional ', 32, 'same-sex marriage, doma, federal law, first circuit, unconstitutional', 'opinion-of-case-finding-doma-unconstitutional', '', 0, 0, ''),
(2, 'primary', 'http://en.wikipedia.org/wiki/Massachusetts_v._United_States_Department_of_Health_and_Human_Services', 1, 'The First Circuit Court of Appeals found that DOMA''s definition of marriage was unconstitutional because the States have traditionally held the power to define marriage, not the federal government. The Supreme Court will probably hear the case soon to ultimately decide DOMA''s fate. ', 'Court Rules DOMA Unconstitutional', 90, 'same-sex marriage, doma, federal law, first circuit, unconstitutional ', 'court-rules-doma-unconstitutional', '', 0, 0, ''),
(3, 'primary', 'http://www.law.cornell.edu/uscode/text/1/7', 1, 'Section 3 of DOMA defines marriage as the legal union between one man and one women. ', 'What the Federal Government Defines as Marriage', 86, 'same-sex marriage, doma, federal law, section 3, marriage defintion', 'what-the-federal-government-defines-as-marriage', '', 0, 0, ''),
(4, 'primary', 'http://www.law.cornell.edu/uscode/text/28/1738C', 1, 'Section 2 of DOMA states that States are not required to recognize another States'' same-sex marriage laws.', 'Section 2 of DOMA', 44, 'same-sex marriage, doma, federal law, section 2, supremacy clause', 'section-2-of-doma', '', 0, 0, ''),
(5, 'secondary', 'http://en.wikipedia.org/wiki/Defense_of_Marriage_Act', 1, 'The Defense of Marriage Act (DOMA) is a federal law that defines marriage as the legal union between one man and one women. It was signed into law in 1996 by President Bill Clinton. Recently the First Circuit found that DOMA is unconstitutional, sparking national debate on the issue of gay rights.', 'Learn more about DOMA', 80, 'same-sex marriage, doma, federal law, Clinton ', 'learn-more-about-doma', '', 0, 0, ''),
(6, 'primary', 'http://caselaw.lp.findlaw.com/data/constitution/amendment10/', 1, 'The 10th Amendment directly from the US Constitution.', 'Tenth Amendment of the US Constitution', 70, 'same-sex marriage, federalism, constitution, tenth amendment  ', 'tenth-amendment-of-the-us-constitution', '', 0, 0, ''),
(7, 'primary', 'http://en.wikipedia.org/wiki/Tenth_Amendment_to_the_United_States_Constitution', 1, 'The Tenth Amendment states the Constitution''s principle of federalism, which delagates powers not granted to the federal government to the States or people. ', 'Learn more about the 10th Amendment', 57, 'same-sex marriage, federalism, constitution, tenth amendment', 'learn-more-about-the-10th-amendment', '', 0, 0, ''),
(8, 'primary', 'http://law-dictionary.clearpointlaw.com/f/federalism_Aut.aspx', 1, 'Federalism is a system of government where State governments and the federal government share power. ', 'Quick Definition of Federalism', 74, '', 'quick-definition-of-federalism', '', 0, 0, ''),
(9, 'primary', 'http://rightdirection.com/2011/05/05/federalism-explained/', 1, 'Federalism divides power between the federal government and States. This gives States greater freedom to define and create different laws.', 'Federalism Explained: Why a ', 50, '', 'federalism-explained-why-a', '', 0, 0, ''),
(141, 'photo', 'http://www.plantingempowerment.com/storage/thumbnails/6628851-17520211-thumbnail.jpg?__SQUARESPACE_CACHEVERSION=1333726618592', 1, 'On April 5, 2012, Obama signed into law the Jumpstart Our Business Startups (JOBS) Act. The bill, among other things, enables startups to raise equity financing for their businesses through crowdfunding platforms. ', 'Jobs Act', 98, 'jobs act, crowdfunding', 'jobs-act', '', 0, 0, ''),
(10, 'primary', 'http://en.wikipedia.org/wiki/Federalism_in_the_United_States', 1, 'Federalism defines the relationship between State governments and the federal government. Certain powers are reserved for the States, whereas others are controlled by the federal government. Some powers are shared. States have traditionally held the exclusive power to define marriage. Thus, DOMA''s definition of marriage may be unconstitutional because it is a State power, not a federal power. ', 'Learn more about Federalism', 80, 'same-sex marriage, federalism ', 'learn-more-about-federalism', '', 0, 0, ''),
(11, 'primary', 'http://usgovinfo.about.com/od/rightsandfreedoms/a/federalism.htm', 1, 'The federal government and State governments have certain exclusive and shared powers. Some exclusive federal government powers include the power to print money, declare war, establish an army and navy, and regulate commerce between the states. Some exclusive State powers include the power to issue licenses, conduct elections, and provide for public health and safety. Some shared powers include setting up courts, creating and collecting taxes, and building highways. ', 'Exclusive Powers of State Governments', 78, 'same-sex marriage, federalism, states'' rights ', 'exclusive-powers-of-state-governments', '', 0, 0, ''),
(12, 'Primary', 'http://www.law.cornell.edu/supct/html/historics/USSC_CR_0017_0316_ZS.html', 1, '', 'Landmark Case Establishing Federalsim', 24, '', 'landmark-case-establishing-federalsim', '', 0, 0, ''),
(13, 'primary', 'http://en.wikipedia.org/wiki/Same-sex_marriage_in_California', 1, 'California use to grant same-sex marriages licenses starting in June 16, 2008. However due to the passage of Proposition 8, same-sex marriage licenses were discontinued in November 5, 2008.', 'Learn More About Gay Marriage in California', 70, 'same-sex marriage, california, prop 8', 'learn-more-about-gay-marriage-in-california', '', 0, 0, ''),
(14, 'primary', 'http://en.wikipedia.org/wiki/California_Proposition_8', 1, 'Proposition 8 was ballot passed in the November 2008 election. It added an amendement to the California Constitution, which provides that "only marriage between a man and a woman is valid or recognized in California."', 'Learn more about Proposition 8', 64, 'same-sex marriage, california, prop 8,', 'learn-more-about-proposition-8', '', 0, 0, ''),
(16, 'primary', 'http://law.onecle.com/california/constitution/article_1/7.5.html', 1, 'Article 1, Section 7.5 of the California Constitution states that California only recognizes marriage between a man and a woman. ', 'Legal Definition of Marriage in California', 68, 'same-sex marriage, california, california constitution, marriage definition', 'legal-definition-of-marriage-in-california', '', 0, 0, ''),
(22, 'primary', 'http://statesthatallowgaymarriage.com/', 1, 'The status of same-sex marriage varies in different states. This is because states have traditionally reserved the right to define marriage. Click on a state for a detailed summary of that State''s same-sex marriage laws. ', 'Same-sex Marriage Facts For Every State', 85, 'same-sex marriage, states, legal status ', 'same-sex-marriage-facts-for-every-state', '', 0, 0, ''),
(18, 'Primary', 'http://www.law.cornell.edu/constitution/amendmentxiv/', 1, '', 'Fourteenth Amendment of the US Constitution', 35, '', 'fourteenth-amendment-of-the-us-constitution', '', 0, 0, ''),
(19, 'primary', 'http://en.wikipedia.org/wiki/Fourteenth_Amendment_to_the_United_States_Constitution', 1, 'The Fourteenth Amendment is composed of several clauses including Due Process, Equal Protection, and Citizenship.', 'Learn more about the 14th Amendment', 56, 'same-sex marriage, constitution, fourteenth amendment, equal protection ', 'learn-more-about-the-14th-amendment', '', 0, 0, ''),
(20, 'primary', 'http://en.wikipedia.org/wiki/Same-sex_marriage_status_in_the_United_States_by_state', 1, 'As of July 10, 2012, same-sex marriage is legal in Vermont, New Hampshire, Massachusetts, Connecticut, New York, Washington D.C., Iowa, and Washington. ', 'Which States Allow Same Sex Marriage?', 91, 'same-sex marriage, states, legal status ', 'which-states-allow-same-sex-marriage', '', 0, 0, ''),
(21, 'primary', 'http://www.ca9.uscourts.gov/datastore/general/2012/02/07/1016696com.pdf', 1, 'The Ninth Circuit Court of Appeals ruled that Proposition 8 was unconstitutional because it''s sole purpose was to deny the right of marriage to gay couples, thereby violating the Fourteenth Amendment.', 'Opinion of Case Finding Prop 8 Unconstitutional ', 24, 'same-sex marriage, california, ninth circuit, prop 8, unconstitutional, fourteenth amendment', 'opinion-of-case-finding-prop-8-unconstitutional', '', 0, 0, ''),
(23, 'news', 'http://www.huffingtonpost.com/2012/07/11/pelosi-house-dems-doma-repeal_n_1665621.html?utm_hp_ref=politics&ir=Politics', 1, 'Led by Minority Leader Nancy Pelosi (D-Calif.), 132 House Democrats filed a brief in the Ninth Circuit Court of Appeals on Tuesday arguing that the Defense of Marriage Act (DOMA) is discriminatory and unconstitutional. In the brief, which was filed in the case of Golinski v. U.S. Office of Personnel Management, the members of Congress argued that DOMA "lacks a rational relationship to any legitimate federal purpose and accordingly is unconstitutional."', 'Nancy Pelosi And House Democrats File Brief Supporting DOMA Repeal In California Court', 90, 'doma, federal law, repeal, democracts', 'nancy-pelosi-and-house-democrats-file-brief-supporting-doma-repeal-in-california-court', '', 0, 0, ''),
(24, 'photo', 'http://statesthatallowgaymarriage.com/wp-content/themes/Gay%20Marriage/images/garymap.gif', 1, 'As of June 2012, eight states recognize or will soon recognize same-sex marriages, and a total of six (plus the District of Columbia) recognize some form of same-sex civil unions or domestic partnerships.', 'States That Allow Gay Marriage', 100, 'same-sex marriage, states, legal status ', 'states-that-allow-gay-marriage', '', 0, 0, ''),
(62, 'secondary', 'http://startuplawyer.com/incorporation/the-when-to-incorporate-decision-matrix', 2, 'Incorporate when you are serious about making your startup a business.  You might want to incorporate when you are working full-time on the start up, hiring employees, seeking seed or venture capital, are high-risk for a lawsuit, granting stock options, and have more than 1 founder. Check out the following decision matrix for a quantitative approach. ', 'When To Incorporate', 73, 'corporation, formation', 'when-to-incorporate', '', 0, 0, ''),
(44, 'primary', 'http://www.supremecourt.gov/opinions/11pdf/11-393c3a2.pdf', 1, 'National Federation of Independent Business v. Sebelius (2012). Supreme Court rules that individual mandate is constitutional under the taxation clause of the US Constitution', 'Individual Mandate is Constitutional!', 40, 'healthcare reform, supreme court, individual mandate, taxing power', 'individual-mandate-is-constitutional', '', 0, 0, ''),
(37, 'photo', 'http://healthreform.kff.org/~/media/Images/KHS/Flowcharts/requirement_flowchart_2.gif?w=800&h=1041&as=1', 1, 'The individual mandate is a provision part of the Affordable Care Act, also know as Obamacare. It requires most people to have health insurance coverage or face a penalty. The conditions are briefly outlined in this flowchart. ', 'Individual Mandate', 81, 'healthcare reform, individual mandate, obamacare', 'individual-mandate', '', 0, 0, ''),
(38, 'secondary', 'http://en.wikipedia.org/wiki/Individual_mandate', 1, 'The individual mandate is a provision in the Affordable Care Act (2010). It imposes a penalty on individuals required to have health insurance coverage. The law will come into effect in 2014 has generated substantial controversy. However, the Supreme Court has ruled that the provision is constitutional under the ''taxing power'' designated to Congress by the Constitution. ', 'Learn More About the Individual Mandate', 47, 'healthcare reform, individual mandate, taxing power, health insurance', 'learn-more-about-the-individual-mandate', '', 0, 0, ''),
(39, 'primary', 'http://www.law.cornell.edu/uscode/text/26/5000A', 1, 'in the Affordable Care Act 26 USC § 5000A', 'Individual Mandate: 26 USC § 5000A', 54, 'healthcare reform, individual mandate, affordable care act, penalty, tax', 'individual-mandate-26-usc-5000a', '', 0, 0, ''),
(40, 'secondary', 'http://en.wikipedia.org/wiki/Patient_Protection_and_Affordable_Care_Act', 1, 'Summary', 'Long Summary of Patient Protection and Affordable Care Act (2010)', 63, 'healthcare reform, affordable care act, obamacare', 'long-summary-of-patient-protection-and-affordable-care-act-2010', '', 0, 0, ''),
(41, 'secondary', 'http://www.kff.org/healthreform/upload/8023-R.pdf', 1, 'The Affordable Care Act (2010), also known as Obamacare contains many provisions on healthcare reform including: an individual mandate requiring most individuals to have health insurance, employer requirements, new regulations to private insurance providers, an expansion of Medicaid, and Health Benefit Exchanges. ', 'Obamacare Basics', 92, 'healthcare reform, affordable care act, obamacare, medicaid', 'obamacare-basics', '', 0, 0, ''),
(42, 'secondary', 'http://www.gpo.gov/fdsys/pkg/PLAW-111publ148/pdf/PLAW-111publ148.pdf', 1, 'Patient Protection and Affordable Care Act (2010)', 'The Law: Patient Protection and Affordable Care Act (2010)', 21, 'healthcare reform, affordable care act, obamacare, health insurance', 'the-law-patient-protection-and-affordable-care-act-2010', '', 0, 0, ''),
(43, 'secondary', 'http://www.healthcare.gov/law/timeline/index.html', 1, 'The Affordable Care Act will be implemented in phases over the next three years. One big event coming up is that in 2014 a tax will be imposed on individuals without healthcare coverage. Check out this cool timeline to see when and what changes are being implemented. ', 'Obamacare: Cool Time Line', 84, 'healthcare reform, affordable care act, obamacare, timeline, ', 'obamacare-cool-time-line', '', 0, 0, ''),
(45, 'secondary', 'http://en.wikipedia.org/wiki/National_Federation_of_Independent_Business_v._Sebelius', 1, 'Summary of Case That Validated the Individual Mandate', 'Summary of Case That Validated the Individual Mandate', 65, 'healthcare reform, supreme court, individual mandate, taxing power', 'summary-of-case-that-validated-the-individual-mandate', '', 0, 0, ''),
(46, 'secondary', 'http://en.wikipedia.org/wiki/Taxing_and_Spending_Clause', 1, 'The Taxing and Spending Clause of the Constitution gives the federal government the power to lay and collect taxes. In June 2012, The Supreme Court used this clause to validate the constitutionality of the individual mandate part of Obamacare. It reasoned that the penalty imposed by the act is a tax, and therefore legitimate. ', 'Taxing Power of Congress', 48, 'healthcare reform, taxing power, constitution', 'taxing-power-of-congress', '', 0, 0, ''),
(47, 'primary', 'http://www.law.cornell.edu/constitution/articlei#section8', 1, 'U.S. Constitution Article I Ã‚Â§ 8 Clause 1 - Tax and Spending', 'Taxing and Spending in the Constitution', 68, 'healthcare reform, taxing power, constitution', 'taxing-and-spending-in-the-constitution', '', 0, 0, ''),
(48, 'news', 'http://www.tax.com/taxcom/features.nsf/Articles/1A096E99F74042BC8525766D005D5147?OpenDocument', 1, 'Featured Articles As if healthcare reform weren''t complex enough, a growing chorus of legal commentators is raising alarms that the tax provisions of the mammoth healthcare bills that have cleared the House and the Senate Finance Committee would violate the Constitution. It''s a debate that played out (without resolution) in 1993-1994 during the Clinton administration''s foray into healthcare reform.', 'Healthcare Reform Tax Constitutionality a Hot Topic', 76, 'healthcare reform, taxing power, constitution, debate', 'healthcare-reform-tax-constitutionality-a-hot-topic', '', 0, 0, ''),
(49, 'secondary', 'http://www.hrsa.gov/womensguidelines/', 1, 'The Affordable Care Act expand prevention coverage for women covering services such as HPV testing, mammograms, screenings, prenatal care, and other services. These will be covered with no cost sharing for the new health plan.', 'Obamacare: Preventative Healthcare for Women', 69, 'healthcare reform, women, obamacare', 'obamacare-preventative-healthcare-for-women', '', 0, 0, ''),
(50, 'news', 'http://politicalticker.blogs.cnn.com/2012/07/09/perry-texas-will-stand-against-obamacare/', 1, '(CNN) - Texas Gov. Rick Perry announced Monday the Lone Star State will not execute major parts of the Affordable Care Act, the controversial federal health care law recently upheld by the Supreme Court.', 'Perry: Texas will stand against ''Obamacare''', 94, 'healthcare reform, texas, perry, obamacare', 'perry-texas-will-stand-against-obamacare', '', 0, 0, ''),
(51, 'news', 'http://politicalticker.blogs.cnn.com/2012/07/09/perry-texas-will-stand-against-obamacare/', 1, '(CNN) - Texas Gov. Rick Perry announced Monday the Lone Star State will not execute major parts of the Affordable Care Act, the controversial federal health care law recently upheld by the Supreme Court.', 'Perry: Texas will stand against ''Obamacare''', 72, 'healthcare reform, texas, perry, obamacare', 'perry-texas-will-stand-against-obamacare', '', 0, 0, ''),
(52, 'news', 'http://www.cnn.com/2012/07/10/politics/house-health-care/', 1, 'Washington (CNN) -- House Republicans launched an all-out assault Tuesday against President Barack Obama''s signature health care reform law, holding a series of committee hearings and other events ahead of a planned vote Wednesday on repealing the measure.', 'House debate on health care repeal: Boss Hogg or Groundhog Day? - CNN.com', 61, 'healthcare reform, texas, perry, obamacare', 'house-debate-on-health-care-repeal-boss-hogg-or-groundhog-day-cnncom', '', 0, 0, ''),
(53, 'news', 'http://www.washingtonpost.com/blogs/she-the-people/post/rick-perry-upholds-the-right-of-texans-to-have-the-worst-health-care-in-the-country/2012/07/10/gJQAblcTaW_blog.html', 1, 'Posted at 11:45 AM ET, 07/10/2012 DALLAS - Texas has the sovereign right to keep the very worst health care in the country, Gov. Rick Perry insisted on Monday.', 'Rick Perry upholds the right of Texans to have the worst health care in the country', 75, 'healthcare reform, texas, perry, obamacare', 'rick-perry-upholds-the-right-of-texans-to-have-the-worst-health-care-in-the-country', '', 0, 0, ''),
(54, 'news', 'http://www.nytimes.com/2012/07/10/us/politics/perry-says-texas-rejects-health-law-intrusions.html?_r=1', 1, 'HOUSTON - Gov. Rick Perry of Texas told federal officials on Monday that the state had no intention of expanding Medicaid or establishing a health insurance exchange, two major provisions of President Obama''s health care overhaul.', 'Perry Says Texas Rejects Health Law ''Intrusions''', 51, 'healthcare reform, texas, perry, obamacare', 'perry-says-texas-rejects-health-law-intrusions', '', 0, 0, ''),
(56, 'secondary', 'http://nhfreedomtomarry.org/resources/doma-explained/', 1, 'The Defense of Marriage Act (DOMA) is a federal law signed by President Bill Clinton in 1996. Section 2 of the law  defines marriage as the legal union between one man and one woman. Section 3 says that States do not have to recognize same-sex marriage laws of another State. Under the Supremacy Clause of the Constitution, States usually have to recognize and respect another State''s laws. However, DOMA says this is not necessary in the case of same-sex marriage. The law has generated controversy and at least one court has found DOMA unconstitutional. ', 'What is DOMA?', 97, 'same-sex marriage, doma, federal law, Clinton ', 'what-is-doma', '', 0, 0, ''),
(57, 'primary', 'http://www.article-3.com/doma-challenge-unites-gay-rights-and-states-rights-97967', 1, 'The Defense of Marriage Act, or DOMA, is a 1996 law that defines marriage as the legal union of one man and one woman. Sixteen years later, the question (as with the recent healthcare battle) is whether this federal law is constitutional or not -- more specifically, whether the federal government has the right to interfere with the workings of state governments.', 'DOMA Challenge Unites Gay Rights and States'' Rights', 57, 'doma, federal law, federalism, states'' rights', 'doma-challenge-unites-gay-rights-and-states-rights', '', 0, 0, ''),
(58, 'news', 'http://www.huffingtonpost.com/nigel-barber/gay-marriage-young-people_b_1659360.html', 1, 'If you want to know what the future holds, talk to young people. On social issues, young American adults today are far more liberal than their parents. The majority support gay marriage (50 percent in favor versus 36 percent against with the remainder undecided.)', 'Is the Debate on Gay Marriage Effectively Over?', 84, 'same-sex marriage, debate, liberal, support', 'is-the-debate-on-gay-marriage-effectively-over', '', 0, 0, ''),
(60, 'news', 'http://www.washingtonblade.com/2012/07/11/romney-stresses-same-sex-marriage-opposition-in-naacp-speech/', 1, 'Presumptive Republican presidential nominee Mitt Romney stressed during a speech at the National Association for the Advancement of Colored People''s annual convention in Houston on Wednesday that he would represent Americans of "every race, creed and sexual orientation" if elected. The former Massachusetts governor also stressed his opposition to nuptials for gays and lesbians.', 'Romney stresses same-sex marriage opposition in NAACP speech', 77, 'same-sex marriage, romney, opposition, NAACP', 'romney-stresses-same-sex-marriage-opposition-in-naacp-speech', '', 0, 0, ''),
(59, 'news', 'http://www.upi.com/Top_News/US/2012/07/11/Gay-marriage-referendum-on-ballot-in-Maryland/UPI-95111342038537/?spt=hts&or=4', 1, 'ANNAPOLIS, Md., July 11 (UPI) -- Maryland voters will be able to decide in November if the state''s new law legalizing same-sex marriage will stand. The state Board of Elections announced Tuesday the Maryland Marriage Alliance, which opposes the law, had gathered enough valid signatures for certification, The Baltimore Sun reported.', 'Gay marriage referendum on ballot in Maryland', 26, 'same-sex marriage, Maryland, ballot, referendum ', 'gay-marriage-referendum-on-ballot-in-maryland', '', 0, 0, ''),
(61, 'news', 'http://www.care2.com/causes/facebook-gay-marriage-icons-provoke-russian-ban-campaign.html', 1, 'Conservative religious groups in Russia are campaigning to ban Facebook and return the nation to its criminalization of homosexuality after Facebook created new icons so users could show they are in a same-sex marriage. The campaign was launched in Saratov and several other Russian regions - including St Petersburg, Novosibirsk and Arkhangelsk - where gay propaganda is banned by law.', 'Anti-Gay Russians Boycott Facebook', 49, 'same-sex marriage, boycott, facebook, russian', 'anti-gay-russians-boycott-facebook', '', 0, 0, ''),
(63, 'secondary', 'http://startuplawyer.com/incorporation/what-is-four-years-with-a-one-year-cliff', 2, 'Four Years with a One Year Cliff is the typical vesting schedule for startup founders’ stock. The one year cliff means that none of the founder''s shares will vest until after one year. After the cliff, shares gradually vest. After 4 years from issuance, all shares vest. ', 'What is Four Years With a One Year Cliff', 54, 'corporation, formation, founders, stock ', 'what-is-four-years-with-a-one-year-cliff', '', 0, 0, ''),
(64, 'primary', 'http://www.law.cornell.edu/uscode/text/26/83', 2, 'If stock vests overtime, each vesting milestone is a taxable event for the founder. The amount taxed is the difference between the fair market value of the stock vesting and the original purchase price of that stock. However, to avoid this potentially disastrous tax consequence, a founder should make an 83(b) which prevents this. Section 83 in Title 26, Chapter 1 of the United States Code codifies this. ', '83(b) Election: 26 USC § 83(b)', 14, 'corporation, formation, tax, founders, stock ', '83b-election-26-usc-83b', '', 0, 0, ''),
(65, 'secondary', 'http://startuplawyer.com/incorporation/the-83b-election-for-startup-founders', 2, 'If stock vests overtime, each vesting milestone is a taxable event for the founder. The amount taxed is the difference between the fair market value of the stock vesting and the original purchase price of that stock. However, to avoid this potentially disastrous tax consequence, a founder should make an 83(b) which prevents this. ', 'Avoid Disastrous Tax Consequences: 83(b) Election', 62, 'corporation, formation, tax, founders, stock ', 'avoid-disastrous-tax-consequences-83b-election', '', 0, 0, ''),
(66, 'primary', 'http://delcode.delaware.gov/title8/c001/sc03/index.shtml', 2, 'Title 8, § 131 requires every Delaware corporation  to maintain a registered agent in Delaware. The registered agent can be an individual, corporation, or another entity. ', 'DE Registered Agent Law', 7, 'corporation, formation, delaware, registered agent', 'de-registered-agent-law', '', 0, 0, ''),
(67, 'secondary', 'http://startuplawyer.com/incorporation/what-is-a-registered-agent', 2, 'A registered agent is someone, either a company or an individual, that a corporation appoints to receive official notices. Corporations must have a registered agent. This agent must be available during normal business hours and is located within the relevant state that they''re registered in. If you fail to update your address or other contact information as a registered agent the secretary of state might become the registered agent. ', 'What is a Registered Agent?', 43, 'corporation, formation, registered agent, llc', 'what-is-a-registered-agent', '', 0, 0, ''),
(68, 'primary', 'https://delecorp.delaware.gov/tin/EntitySearch.jsp', 2, 'Search a name and entity type to see if it is available in Delaware. If it is, you will be able to register that name. ', 'Is Your Startup''s Name Available in Delaware', 89, 'corporation, llc, formation, name search, delaware', 'is-your-startups-name-available-in-delaware', '', 0, 0, ''),
(69, 'secondary', 'http://startuplawyer.com/incorporation/top-5-reasons-to-incorporate-in-delaware', 2, 'Delaware has flexible laws, a well established court for business issues, and relatively cheap fees. For these reasons, over 50% of U.S. publicly traded corporations and 60% of Fortune 500 companies are incorporated in Delaware. ', 'Top 5 Reasons to Incorporate in Delaware', 96, 'incorporation, delaware', 'top-5-reasons-to-incorporate-in-delaware', '', 0, 0, ''),
(70, 'primary', 'http://www.docracy.com/5393/certificate-of-incorporation', 2, 'A certificate of incorporation (COI) is a legal document relating to the formation of a company. It contains a corporation''s articles of incorporation, which are the primary rules governing the management. This is an example of a COI.', 'Example Certificate of Incorporation', 22, 'corporation, formation, document, certificate of incorporation', 'example-certificate-of-incorporation', '', 0, 0, ''),
(71, 'primary', 'http://www.docracy.com/61/restated-articles-of-incorporation', 2, 'A certificate of incorporation (COI) is a legal document relating to the formation of a company. It contains a corporation''s articles of incorporation, which are the primary rules governing the management. If the COI is amended, it must be refiled with the state. This is an example of an amended and restated COI.  ', 'Example Amended and Restated Certificate of Incorporation', 18, 'corporation, formation, document, certificate of incorporation', 'example-amended-and-restated-certificate-of-incorporation', '', 0, 0, ''),
(72, 'secondary', 'http://www.nolo.com/legal-encyclopedia/corporation-basics-29867.html', 2, 'Corporations provide limited liability, which means \nthat creditors of the company can''t go after personal assets of members. However, corporate owners face double taxation because corporate income is taxed separately from personal income. Furthermore, corporations must follow certain formalities to retain its corporate status. ', 'Corporation Basics', 100, 'corporation, formation, limited liability, tax', 'corporation-basics', '', 0, 0, ''),
(73, 'secondary', 'http://www.nolo.com/legal-encyclopedia/corporations-vs-llcs-29025.html', 2, 'A LCC may be preferable for small businesses that prefer a simple and flexible management structure. A corporation may be preferable for businesses that expects to have multiple investors, provide extensive fringe benefits to owners, or offer stock options to employees. ', 'Corporations vs. LLCs', 98, 'corporation, s-corporation, llc', 'corporations-vs-llcs', '', 0, 0, ''),
(74, 'secondary', 'http://startuplawyer.com/incorporation/a-primer-on-llcs', 2, 'A limited liability company (LLC) is a type of legal entity that provides limited liability to its members. Limited liability means that creditors of the company can''t go after personal assets of any members. Members of a LLC can operate their business with a flexible management structure. Furthermore, a LCC is a pass through tax entity, which means that the company''s income is "passed through" to the members, and then taxed. This avoids the problem of double taxation that is typical of corporations. ', 'Quick Overview on LLCs', 100, 'llc, formation, limited liability, tax, management', 'quick-overview-on-llcs', '', 0, 0, ''),
(75, 'secondary', 'http://www.nolo.com/legal-encyclopedia/llc-basics-30163.html', 2, 'A limited liability company (LLC) is a type of legal entity that provided limited liability to its members. Limited liability means that creditors of the company can''t go after personal assets of any member. Members of a LLC can operate their business with a flexible management structure. Furthermore, a LCC is a pass through tax entity, which means that the company''s income is "passed through" to the members, and then taxed. This avoids the problem of double taxation that is typical of corporations.', 'LLC Basics', 91, 'llc, formation, limited liability, tax, management', 'llc-basics', '', 0, 0, ''),
(76, 'secondary', 'http://www.irs.gov/businesses/small/article/0,,id=98277,00.html', 2, 'An LLC is a business structure allowed by state statute. However, the federal government does not recognize it as a separate classification for federal tax purposes. An LLC business entity must file a corporation, partnership or sole proprietorship tax return.', 'LCCs and IRS Classification', 32, 'llc, tax', 'lccs-and-irs-classification', '', 0, 0, ''),
(77, 'secondary', 'http://www.nolo.com/legal-encyclopedia/key-advantages-llc.html', 2, 'LLCs provide flexibility, limited liability, pass-through taxation, and less administrative paperwork.  Most states allow single member LLCs and multiple member LLCs can create their own operating agreements. Like most legal entities, LCCs protect members from liability, which prevents creditors of the company from pursuing person assets of any member. Further, a LCC avoids the double taxation issue because all income is passed through to the members and then taxed. ', 'Key Advantages of an LLC', 95, 'llc, tax, management', 'key-advantages-of-an-llc', '', 0, 0, ''),
(78, 'secondary', 'http://mashable.com/2010/08/02/legal-structure-startup/', 2, 'Information on LLC, S-Corporation, and C-Corporation.', 'HOW TO: Legally Structure your Startup', 87, 'llc, corporation, s-corporation', 'how-to-legally-structure-your-startup', '', 0, 0, ''),
(79, 'secondary', 'https://www.upcounsel.com/Public/Project/4ee287a3be61490db444739b', 2, 'Investors tend to prefer a Delaware Corporation. If the corporation is not incorporated in Delaware, it is advisable to form the corporation in your home state. If you plan on primarily compensating investors through cash disbursements then you should consider forming an LLC. Note that a corporate structure is far more suited for business developers that plan to pay employees, advisers and contractors with equity ownership. Ultimately determining what type of business to form will depend on the pay structure of the corporation and the type of inventory/assets that will be held.', 'Choose A Legal Entity For Your Business', 72, 'llc, corporation, s-corporation', 'choose-a-legal-entity-for-your-business', '', 0, 0, ''),
(80, 'secondary', 'http://startuplawyer.com/incorporation/how-many-shares-should-a-startup-company-authorize-at-incorporation', 2, 'Although the numbers of shares to issue at incorporation is somewhat arbitrary, some people like to have a larger absolute number of stock options.', 'How Many Shares Should a Startup Company Authorize at Incoportation?', 56, 'stock, corporation, formation', 'how-many-shares-should-a-startup-company-authorize-at-incoportation', '', 0, 0, ''),
(81, 'secondary', 'http://startuplawyer.com/incorporation/par-value-for-a-startup-companys-stock', 2, 'Par value is the minimum price that a corporation can issue its shares. Many stocks have a par value of $1. It is recommended that a stock''s par value should be set at $0.0001 to as low as $0.00001. Thus, when a startup issues 7,000,000 shares at $0.0001 value, the founders pay $700.', 'Par Value for a Startup Company''s Stock', 43, 'stock, corporation, formation, par value', 'par-value-for-a-startup-companys-stock', '', 0, 0, ''),
(82, 'secondary', 'http://startuplawyer.com/preferred-stock/what-is-preferred-stock', 2, 'Preferred stock provides certain economic rights such as liquidation preference, anti-dilution protection, and conversion rights. These stocks are commonly issued when a startup undergoes a large financing, such as a venture capital fund. Common and preferred stock differ in that common stock typically gets a lower valuation for the purposes of stock option grants or share issuances to the corporation''s employees.  ', 'What is Preferred Stock?', 69, 'stock, preferred stock, investors', 'what-is-preferred-stock', '', 0, 0, ''),
(83, 'secondary', 'http://www.investopedia.com/ask/answers/182.asp#axzz20AIxv9Ov', 2, 'Preferred stockholders have a greater claim to a company''s assets and earnings, and generally greater dividends than common stock.', 'What is the difference between preferred stock and common stock?', 79, 'stock, preferred stock, common stock', 'what-is-the-difference-between-preferred-stock-and-common-stock', '', 0, 0, ''),
(84, 'secondary', 'http://startuplawyer.com/stock-options/what-is-an-option-pool', 2, 'An option pool is an amount of common stock that''s reserved for future issuances to employees, directors, advisers, and consultants. Unused portions of the option pool is included in the fully-diluted capitalization of the start-up, but the same unused portion isn''t included in the outstanding share count upon an acquisition or distribution. ', 'What is an Option Pool?', 52, 'stock, options', 'what-is-an-option-pool', '', 0, 0, ''),
(85, 'secondary', 'http://www.investopedia.com/university/mergers/', 2, 'A merger is a when two or more companies combine to make one new company. There are several types of mergers including horizontal (companies in direct competition), vertical (supplier and buyer companies), and a conglomeration (two companies that have no common business areas). An acquisition is when one company takes over another, destroying that original company. Mergers and acquisitions are done in order to create synergies and economies of scale, expand operations, and cut costs. Synergies and economies of scale are enhanced cost efficiencies, such as staff reductions, acquiring new technology, and having greater purchasing power.\n', 'Merger and Acquisition Introduction', 31, 'M&A', 'merger-and-acquisition-introduction', '', 0, 0, ''),
(86, 'secondary', 'http://business-law.lawyers.com/buying-selling-businesses/Business-Basics-of-Mergers-and-Acquisitions.html', 2, 'A merger is when two or more businesses join together to create a new business. Each business''s debts and liabilities are combined, as well as any real estate, and become part of the new business. An acquisition is when one business buys or takes over another business. The buying company remains intact in an acquisition. ', 'Business Basics of Mergers and Acquisitions', 86, 'M&A', 'business-basics-of-mergers-and-acquisitions', '', 0, 0, ''),
(87, 'primary', 'https://www.docracy.com/3835/assignment-of-copyright', 2, 'A generic assignment of a copyright application contains information on the two entities and the addresses of each. A description is also included as well as the types of rights that an owner has.', 'Assignment of Copyright', 49, 'ip, copyright, assignment, document', 'assignment-of-copyright', '', 0, 0, ''),
(88, 'secondary', 'http://www.iplawforstartups.com/why-copyright-assignments-can-be-critical-for-startups/', 2, 'Copyright assignments are important because you want to be the owner of copyrighted worked done by independent contractors for your business. Otherwise, the contractor will be the copyright owner and you will need permission to use the work. This is especially important if paid for the work, such as a logo or website design. ', 'Why Copyright Assignments Can Be Critical for Your Company', 75, 'ip, copyright, assignment', 'why-copyright-assignments-can-be-critical-for-your-company', '', 0, 0, ''),
(89, 'secondary', 'http://www.iplawforstartups.com/does-copyright-law-protect-apis-google-and-oracle-want-to-know/', 2, 'A recent case between Google and Oracle has sparked debate as to whether or not API''s should be protected. API''s are a set of instructions that allows software components to talk to one another. Since copyrights do not protect all written expression, API''s could be considered merely methods or operation or interface access buttons. ', 'Does Copyright Law Protect APIs? ', 65, 'ip, copyright, api, google', 'does-copyright-law-protect-apis', '', 0, 0, ''),
(90, 'primary', 'http://www.law.cornell.edu/uscode/text/17/chapter-1', 2, 'Title 17, Chapter 1 of the United States Code contains the laws on copyright. For example, 17 § 102 states that the following can be copyrighted: literary works, musical works, dramatic works, sound recordings, motion pictures, graphics, etc. You can explore the different sections here. ', 'Definition of Copyright', 10, 'ip, copyright, definition', 'definition-of-copyright', '', 0, 0, ''),
(91, 'primary', 'http://www.law.cornell.edu/uscode/text/17/107', 2, 'The fair use exception allows for the limited use of copyrighted materials without permission from the rights holder. It serves as a perfect defense to claims of copyright infringement based on a four-factor balancing test codified in 17 U.S.C. 106A.  Under this statute, the purpose of use may include, but is not limited to “criticism, comment, news reporting, teaching (including multiple copies for classroom use), scholarship, or research.”', 'Fair Use Exception', 17, 'ip, copyright, fair use', 'fair-use-exception', '', 0, 0, ''),
(92, 'secondary', 'https://www.upcounsel.com/Public/Project/4f878344ce77a70bbcd387a6', 2, 'Copyright is...', 'What is Copyright?', 76, 'ip, copyright, register', 'what-is-copyright', '', 0, 0, ''),
(93, 'secondary', 'http://www.uspto.gov/patents/resources/general_info_concerning_patents.jsp#heading-3', 2, 'Essentially, anything man-made and the processes for making these products can be patented. Only the use of special nuclear material or atomic energy in an atomic weapon cannot be patented. Patents must be "new" and "useful." A "useful" item refers to an invention or process that serves a useful purpose and operates/performs in the way that it was designed.', 'What is a Patent?', 61, 'ip, patent', 'what-is-a-patent', '', 0, 0, ''),
(94, 'news', 'http://techcrunch.com/2012/06/21/do-patents-really-matter-to-startups-new-data-reveals-shifting-habits/', 2, 'Arguments about the value of patents have heated up over the past few years. Software patents in particular have come under increasing scrutiny from thought leaders in the start-up ecosystem, yet later-stage companies like Facebook continue to pay huge sums to acquire patent portfolios. Just how much attention are start-ups paying to patents?', 'Do Patents Really Matter To Startups?', 59, 'ip, patent, investors', 'do-patents-really-matter-to-startups', '', 0, 0, ''),
(95, 'secondary', 'http://blog.upcounsel.com/should-i-get-a-patent-for-startups-and-young-companies/', 2, 'There are several things to consider before applying for a patent including: the idea is patentable, is there already a patent out there for the idea, if the idea is better protected with a trade secret, and if it is the right time to get a patent. Timing is very important because you want to make sure that the product will not change before reaching consumers. Otherwise, a lot of money can be wasted filing the patent. ', 'Should I Get A Patent?', 81, 'ip, patent, register', 'should-i-get-a-patent', '', 0, 0, ''),
(96, 'news', 'http://techcrunch.com/2012/04/15/why-startups-should-pay-attention-to-skyrocketing-patent-prices/', 2, 'As large companies increasingly look to protect their revenue streams through IP risk mitigation, startups with strong patent holdings will become increasingly valuable because they provide an opportunity to remove dual potential threats to the potential acquirer''s revenue stream -- as a competitor and as a patent threat.', 'Why Startups Should Pay Attention To Skyrocketing Patent Prices', 50, 'ip, patent', 'why-startups-should-pay-attention-to-skyrocketing-patent-prices', '', 0, 0, ''),
(97, 'secondary', 'http://www.trademarkia.com/', 2, 'A trademark is a distinctive sign or indicator that is used to help consumers identify and distinguish products or services of a specific business or person. A trademark is usually a word, phrase, name, symbol, logo, design, image or combination of the above. Use trademarkia to preform a free search to see if a trademark is available.', 'Free Trademark Search Online', 94, 'ip, trademark, name search', 'free-trademark-search-online', '', 0, 0, ''),
(98, 'primary', 'http://www.law.cornell.edu/uscode/text/15/1052', 2, 'Title 15, Chapter 22 of the United States Code contains the laws on trademarks. You can explore the different sections here. ', 'Law on Registering a Trademark', 15, 'ip, trademark, register', 'law-on-registering-a-trademark', '', 0, 0, ''),
(99, 'primary', 'http://www.uspto.gov/trademarks/index.jsp', 2, 'A trademark is a distinctive sign or indicator that is used to help consumers identify and distinguish products or services of a specific business or person. A trademark is usually a word, phrase, name, symbol, logo, design, image or combination of the above. The main purpose of a trademark is to identify a business as the source of specific goods or services. You are not required to register a trademark and can establish rights over that mark based on legitimate use. ', 'What is a Trademark?', 83, 'ip, patent, trademark, name search', 'what-is-a-trademark', '', 0, 0, ''),
(100, 'primary', 'http://www.uspto.gov/trademarks/basics/index.jsp', 2, 'Trademark, patent, or copyrights protect different aspects of intellectual property. Hiring a trademark attorney will increase the possibility of success when applying for a trademark. Knowing the how the trademark will be used will aid in determining the "basis" in which a trademark should be filed. USPTO maintains a database of registered trademarks.   ', 'Trademark Basics', 74, 'ip, trademark', 'trademark-basics', '', 0, 0, ''),
(102, 'news', 'http://techcrunch.com/2012/06/01/whoshere-vs-wnm-live/', 2, 'So here''s a story that hopefully will be an eye-opener for entrepreneurs and startups, while providing a painful peek into trademark harassment and the importance of due diligence. It goes a little something like this: About two years ago, software engineer Brian Hamachek decided to build an app first on Windows Mobile (how some horror stories have been known to begin), then on Windows Phone, that enables location-based chat -- and calling.', 'Startups Vs. Startups: App Developer Gets Sued By Lightbank-Backed WhosHere', 24, 'ip, trademark, whoshere, litigation, apps', 'startups-vs-startups-app-developer-gets-sued-by-lightbank-backed-whoshere', '', 0, 0, ''),
(103, 'news', 'http://online.wsj.com/article/SB10001424052702304070304577395953754702524.html?KEYWORDS=startup+copyright', 2, 'Venture capitalists, angel investors and start-up lawyers these days tend to be obsessed with "intellectual property," or IP. And for good reason: In the information economy, the core assets of a new venture are likely to be talented people, the IP they create, and little else.', '5 ''IP'' Mistakes Start-ups Should Avoid', 93, 'ip, trademark, patent, copyright', '5-ip-mistakes-start-ups-should-avoid', '', 0, 0, ''),
(104, 'primary', 'http://www.docracy.com/1/generic-nda', 2, 'A Non-disclosure Agreement is a contract between two parties that restricts the sharing of confidential materials to others. It is necessary if a company is sharing confidential information to another person, such as an employee or contractor, and wants that person not to disclose the information to others. This example can be tailored to fit the needs of a startup.  ', 'Generic NDA that can be Tailored', 77, 'document, nda, ip', 'generic-nda-that-can-be-tailored', '', 0, 0, ''),
(105, 'primary', 'https://www.docracy.com/6479/short-nda-for-internet-startup', 2, 'A Non-disclosure agreement (NDA) is a contract between two parties that outlines confidential information that cannot be shared or disclosed to others. They typically protect non-public business information. NDAs are important to make sure a person does not disclose confidential information to others, such as trade secrets. This is a short sample NDA for an internet startup that can be tailored. ', 'Short NDA for Internet Startup', 97, 'document, nda, ip', 'short-nda-for-internet-startup', '', 0, 0, ''),
(106, 'secondary', 'http://www.investopedia.com/terms/n/nda.asp#axzz20jirrd3v', 2, 'A Non-disclosure agreement (NDA) is an agreement between two parties that outlines confidential information that cannot be shared or disclosed to others. It is necessary if a company is sharing confidential information to another person, such as an employee, and wants that person not to disclose the information to others. ', 'What is an NDA?', 95, 'nda', 'what-is-an-nda', '', 0, 0, ''),
(107, 'secondary', 'http://www.ehow.com/how_4456521_write-nondisclosure-agreement.html', 2, 'A non-disclosure agreement (NDA) is a contract where the signer agrees to not disclose proprietary or confidential information about another company. The best way to write an NDA is to determine the worst case scenario and tailor the NDA to prevent that situation from occurring. Consulting a lawyer is heavily advised as this agreement will protect your company from costly law suits in the future.', 'How to Write an NDA', 63, 'nda', 'how-to-write-an-nda', '', 0, 0, ''),
(108, 'primary', 'http://contracts.onecle.com/type/21.shtml', 2, 'A Non-compete is a contract used to stop a person (usually an employee) from pursuing a similar profession or trade in competition against a company. This is important because upon termination the employee might begin working for a competitor or start a business that is in direct competition with the original company, and use knowledge gained from that original company to his or her advantage. Here are examples of non-compete agreements that can be tailored to fit your needs.     ', 'Example Non-compete Agreements', 33, 'document, non-compete', 'example-non-compete-agreements', '', 0, 0, ''),
(109, 'secondary', 'http://www.ehow.com/how_4486945_write-noncompete-agreement.html', 2, 'A Non-compete is a contract used to stop a person (usually an employee) from pursuing a similar profession or trade in competition against a company. In writing a Non-compete Agreement it is important to define what the employee or contractor can or cannot do. It is also a good idea to include a non-consulting clause and a penalty clause in case the agreement is broken. Check out examples to help you write your non-compete. ', 'How to Write a Non-compete Agreement', 35, 'non-compete', 'how-to-write-a-non-compete-agreement', '', 0, 0, ''),
(110, 'primary', 'http://www.docracy.com/48/technology-assignment-agreement', 2, 'A Technology Assignment Agreement or IP Assignment Agreement transfers IP rights to your company with respect to work produced by an employee or contractor. Otherwise, the employee or contractor will be the copyright holder and you will need permission to use the work. Therefore, it''s important to make sure you have these documents. Here is an example of a Technology Assignment Agreement. ', 'Technology Assignment Agreement', 21, 'ip, document, ip assignment', 'technology-assignment-agreement', '', 0, 0, ''),
(111, 'primary', 'http://www.docracy.com/6480/short-ip-assignment-agreement-for-internet-startup', 2, 'An IP Agreement transfers to the company all IP rights of what an employee or contractor produces.', 'IP Assignment Agreement', 78, 'ip, document, ip assignment', 'ip-assignment-agreement', '', 0, 0, ''),
(112, 'secondary', 'http://www.baercrossey.com/892/startup-killer', 2, 'Investors typically dislike to invest in a company that doesn''t have exclusive ownership of its IP. For this reason, it is important to have IP Assignment and Non-disclosure Agreements (NDA) from your employees and contractors. An IP Assignment Agreements transfers to the company IP rights to work product created by the employee or contractor. A NDA is used to make sure that the employee or contractor does not disclose confidential information to third parties about any non-public business information.', 'Startup Killer: Not Getting Confidentiality/IP Assignment Agreements From Employees and Contractors', 89, 'ip, ip assignment, nda', 'startup-killer-not-getting-confidentialityip-assignment-agreements-from-employees-and-contractors', '', 0, 0, '');
INSERT INTO `links` (`id`, `type`, `url`, `category`, `summary`, `title`, `votes`, `tags`, `slug`, `source`, `poster`, `date_created`, `location`) VALUES
(113, 'primary', 'http://www.docracy.com/42/docracy-terms-of-service-1-', 2, 'Terms of Service are rules which a user must agree to abide by in order to use a service. Commonly, Terms of Service will have rules in which visitors have to follow. Different types of websites will have different kinds of Terms of Service. This is an example of Terms of Service for Docracy.', 'Terms of Service for Your Website', 42, 'document, terms of service, website', 'terms-of-service-for-your-website', '', 0, 0, ''),
(114, 'secondary', 'http://en.wikipedia.org/wiki/Terms_of_service', 2, 'Terms of Use are rules that a user must agree to abide by in order to use a service. A disclaimer is often found within a Terms of Use. Websites that require a high level of community trust or handle transactions involving money tend to have carefully designed terms of service. ', 'Terms of Service Overview', 60, 'terms of service', 'terms-of-service-overview', '', 0, 0, ''),
(115, 'secondary', 'http://www.dot.jo/why-are-privacy-policies-and-terms-use-important-website', 2, 'Terms of use often contain information about price and/or content changes on a website. These terms should inform visitors that information can change without notice and as an owner of the website you set the rules.  ', 'Why are privacy policies and terms of use important for a website?', 71, 'privacy policy, terms of service', 'why-are-privacy-policies-and-terms-of-use-important-for-a-website', '', 0, 0, ''),
(116, 'primary', 'http://www.docracy.com/25/wordpress-privacy-policy-', 2, 'A privacy policy is used to inform visitors what type of information will be collected from them. This legal document discloses some or all of the ways a party gathers, uses, discloses, and manages a customer or client''s data. This is a sample of WordPress.org''s privacy policy and contains the common issues that privacy policies should contain.  ', 'Privacy Policy', 36, 'privacy policy, document, website', 'privacy-policy', '', 0, 0, ''),
(117, 'secondary', 'http://www.privacytrust.org/guidance/privacy_policy.html', 2, 'A privacy policy is one of the most important documents on any website. It details your company''s views and procedures on the information collected from visitors. Although a privacy policy is technically a legal document, great effort should be made to craft a document that is both accurate and easy to understand, obscuring hidden clauses in reams of text is not acceptable.', 'Importance of a Privacy Policy', 66, 'privacy policy', 'importance-of-a-privacy-policy', '', 0, 0, ''),
(118, 'secondary', 'http://www.markwelchblog.com/2010/11/10/why-is-a-privacy-policy-important/', 2, 'Websites that do not have a privacy policy are seen as less professional and not as trustworthy. Consumers constantly evaluate the types of websites they visit. A reputable or trustworthy website will often have a "privacy policy," "about us," and "contact us" section.  ', 'Why Is a Privacy Policy Important?', 55, 'privacy policy, website', 'why-is-a-privacy-policy-important', '', 0, 0, ''),
(119, 'secondary', 'http://blog.upcounsel.com/hiring-interns/', 2, 'There are federal requirements that must be followed in order to legally use unpaid interns. This includes: 1) the internship is similar to training given in an educational environment; 2) the internship is for the benefit of the intern; 3) the intern does not replace regular employees and works under close supervision; 4) the employer does not receive any immediate advantage from the intern and is occasionally slowed down by the intern; 5) the intern is not entitled to a job at the end of the internship; and 6) the employer and intern understand that the intern is not entitled to wages. California has additional requirements.', 'The Basics Of Hiring Interns For Your Startup', 92, 'interns', 'the-basics-of-hiring-interns-for-your-startup', '', 0, 0, ''),
(120, 'secondary', 'http://www.dol.gov/whd/regs/compliance/whdfs71.htm', 2, 'Six criteria must be met in order to legally hire an unpaid intern. To determine whether or not the internship is legal depends on the type of program offered to the intern. Ultimately as long as the program benefits the intern it will conform the the Fair Labor Act. ', 'Before You Hire an Intern, Make Sure you Meet the Following Conditions', 52, 'interns', 'before-you-hire-an-intern-make-sure-you-meet-the-following-conditions', '', 0, 0, ''),
(121, 'news', 'http://techcrunch.com/2012/06/10/startup-act-2-0-great-for-foreign-graduate-students-but-not-foreign-tech-entrepreneurs/', 2, 'Immigration and startups...', 'Startup Act 2.0: Great For Foreign Graduate Students, But Not Foreign Tech Entrepreneurs', 19, 'immigration', 'startup-act-20-great-for-foreign-graduate-students-but-not-foreign-tech-entrepreneurs', '', 0, 0, ''),
(122, 'news', 'http://techcrunch.com/2012/03/16/crowdfundingstartups/', 2, 'Last week, the U.S. House of Representatives passed the JOBS Act, a bipartisan bill aimed at supporting small businesses by making it easier for them to access capital. A key feature of the bill enables crowdfunding, the process by which small companies raise growth capital from a large number of individual investors.', 'How The JOBS Act Could Change Startup Investing Forever', 58, 'jobs act, investors', 'how-the-jobs-act-could-change-startup-investing-forever', '', 0, 0, ''),
(123, 'news', 'http://www.forbes.com/sites/theyec/2012/07/13/10-common-pitfalls-of-new-entrepreneurs-and-how-to-avoid-them/', 2, 'Starting a business is pretty tricky for the uninitiated, and what you don''t know can be disastrous. Most small business fail within the first five years, but that''s often because of easily avoidable mistakes. If you''re planning to start a new business, especially one that''s service-based, here are some pointers to help you avoid some of the most common startup pitfalls: Use a contract.', '10 Common Pitfalls of New Entrepreneurs - and How to Avoid Them', 85, '', '10-common-pitfalls-of-new-entrepreneurs-and-how-to-avoid-them', '', 0, 0, ''),
(124, 'primary', 'https://www.upcounsel.com/Public/Overview/4f6a8156be61497c3c59c585', 2, 'When you add an advisor to your company, it is important to follow several steps: execute a mutual non-disclosure agreement, decide how much equity you will give the advisor, execute an advisory agreement, decide whether to compensate the advisor with options or restricted stock. You can negotiate the exact terms between you and the advisor. ', 'How to Add an Advisor', 39, 'advisor, nda', 'how-to-add-an-advisor', '', 0, 0, ''),
(125, 'primary', 'http://www.law.cornell.edu/constitution/articlei#section8', 1, 'The federal government has reserved the right to regulate immigration, although it is not explicitly mentioned in the Constitution. The power is an extension of its explicit right to establish the rules of naturalization. Naturalization Clause: Article I Â§ 8 Clause 4.    ', 'The Federal Government Regulates Immigration: Not States', 70, 'immigration, constitution', 'the-federal-government-regulates-immigration-not-states', '', 0, 0, ''),
(126, 'primary', 'http://supreme.justia.com/cases/federal/us/426/88/case.html', 1, 'Hampton v. Mow Sun Wong - 426 U.S. 88 (1976)', 'Case That Affirmed the Federal Government''s Right to Regulate Immigration ', 12, 'immigration, federal', 'case-that-affirmed-the-federal-governments-right-to-regulate-immigration', '', 0, 0, ''),
(127, 'primary', 'http://www.dhs.gov/xlibrary/assets/s1-exercising-prosecutorial-discretion-individuals-who-came-to-us-as-children.pdf', 1, 'The Secretary of Homeland Security, Janet Napolitano, wrote a memo outlining the department''s new policy to not prosecute illegal aliens who were brought into this county as children. In order to qualify, the person 1) entered the US under the age of sixteen, 2) has continuously lived in the US for at least five years, 3) is currently in school, graduated high school, or obtained a general education development certificate, 4) has not been convicted serious or multiple crimes, 5) is not above the age of thirty. The department is allowed to do this because it has discretion in prosecuting immigrants.', 'Obama: Illegal Children Will Not be Deported', 82, 'immigration, obama', 'obama-illegal-children-will-not-be-deported', '', 0, 0, ''),
(128, 'secondary', 'http://dreamact.info/', 1, 'The DREAM Act (Development, Relief, and Education for Alien Minor, is a bill that provides conditional permanent residency to certain illegal individuals. The individuals must have arrived in the US as minors, have lived in the US continuously for five years, and graduate from high school. The bill was first introduced in 2001 and has yet to pass.', 'What is the DREAM Act?', 71, 'immigration, dream act', 'what-is-the-dream-act', '', 0, 0, ''),
(129, 'secondary', 'http://www.youtube.com/watch?v=MXnqhG2h9QA', 1, 'Video on the DREAM Act', 'A Dream Act Infographic', 60, 'immigration, dream act', 'a-dream-act-infographic', '', 0, 0, ''),
(130, 'photo', 'http://www.stokelybaksh.com/wp-content/uploads/2011/08/state_legislations_CL.jpg', 1, 'In the past couple years, several States, including Arizona and Alabama, have taken anti-illegal immigration measures. Such bills have been challenged under constitutional and civil rights protections. In 2012, the Supreme Court struck down several provisions part of Arizona''s controversial immigration law because they violated the Supremacy Clause of the Constitution. However, the status of illegal immigrants remain uncertain under the Obama administration. ', 'Immigration Reform', 99, 'immigration, states', 'immigration-reform', '', 0, 0, ''),
(131, 'primary', 'http://www.azdatapages.com/sb1070.html', 1, 'AArizona - summary of SB 1070 and Supreme Court case', 'Arizona''s Controversial Immigration Law', 45, 'immigration, arizona', 'arizonas-controversial-immigration-law', '', 0, 0, ''),
(132, 'secondary', 'http://en.wikipedia.org/wiki/Arizona_SB_1070', 1, 'Arizona SB 1070 is an anti-illegal immigration bill signed into law in 20120. It has received national attention for its strict regulations and encouragement of racial profiling. Some of its provisions included: an alien must carry required documents at all time and the police can investigate a person''s immigration status during a legal stop. In June 2012, the Supreme Court struck down some of the bill''s provisions as unconstitutional.   ', 'Overview of Arizona''s Controversial Immigration Law', 85, 'immigration, arizona', 'overview-of-arizonas-controversial-immigration-law', '', 0, 0, ''),
(133, 'primary', 'http://www.supremecourt.gov/opinions/11pdf/11-182b5e1.pdf', 1, 'The Supreme Court...', 'Arizona''s Immigration Law Ruled Unconstitutional', 63, 'immigration, arizona, supreme court, unconstitutional', 'arizonas-immigration-law-ruled-unconstitutional', '', 0, 0, ''),
(134, 'secondary', 'http://en.wikipedia.org/wiki/Arizona_v._United_States', 1, 'In Arizona v. United States, 567 U.S. ___ (2012), the Supreme Court ruled that some provisions of Arizona''s anti-illegal immigration (Arizona SB 1070) bill were unconstitutional under the theory of federal preemption. The federal government has the authority to regulate immigration. However, Arizona passed regulations that conflicted with federal law. Thus, those regulations were found to be invalid. The three provisions struck down: 1) required immigrants to carry legal documents at all times; 2) allowed police to arrest any person for suspicion of being an illegal immigrant; and 3) made it a crime for an illegal immigrant to search for a job. ', 'The Supreme Court Case That Invalided Arizona''s Immigration Law', 78, 'immigration, arizona, supreme court, unconstitutional', 'the-supreme-court-case-that-invalided-arizonas-immigration-law', '', 0, 0, ''),
(135, 'primary', 'http://latindispatch.com/2011/06/09/text-of-alabama-immigration-law-hb-56/', 1, 'Alabama HB 56 ', 'Alabama''s Controversial Immigration Law', 40, 'immigration, alabama', 'alabamas-controversial-immigration-law', '', 0, 0, ''),
(136, 'secondary', 'http://en.wikipedia.org/wiki/Alabama_HB_56', 1, 'Alabama HB 56 is an anti-immigration bill, signed into law in June 2011. Some of its provisions include: allows officers to attempt to investigate a person''s immigration status midst any legal stop, requires public schools to ascertain the immigration status of students, prohibits landlords from renting property to illegal aliens, etc. Its regulations are stricter than Arizona''s anti-immigration bill, which received national attention in summer 2012. ', 'Overview of Alabama''s Controversial Immigration Law', 93, 'immigration, alabama', 'overview-of-alabamas-controversial-immigration-law', '', 0, 0, ''),
(137, 'primary', 'http://caselaw.lp.findlaw.com/data/constitution/article06/', 1, 'Federal laws may invalidate conflicting State laws. This is laid down in the Supremacy Clause of the Constitution and is called federal premption. In the case of immigration laws...', 'Supremacy Clause and Immigration', 60, 'immigration, supremacy clause, constitution', 'supremacy-clause-and-immigration', '', 0, 0, ''),
(138, 'secondary', 'http://www.immigrationworksusa.org/index.php?p=192', 1, 'Federal preemption is a legal term used to describe a situation where a federal law invalidates a State law. This  usually happens when there is a State law that conflicts with a federal law. Federal preemption is derived from the Supremacy Clause in the Constitution, which declares that federal law is the supreme law of the land. ', 'Federal Preemption Invalidates State Immigration Laws', 87, 'immigration, federal preemption', 'federal-preemption-invalidates-state-immigration-laws', '', 0, 0, ''),
(139, 'secondary', 'http://legal-dictionary.thefreedictionary.com/Supremacy+Clause', 1, 'The supremacy clause is...It affects immigration because...', 'What is the Supremacy Clause?', 39, 'immigration, supremacy clause', 'what-is-the-supremacy-clause', '', 0, 0, ''),
(140, 'photo', 'http://3.bp.blogspot.com/_N_aDa0MnjQE/S9jnIqCWQwI/AAAAAAAAAGI/Z7wZ_LLlB2c/s1600/transparency-1.jpg', 1, 'In 2010, Obama signed into law the Patient Protection and Affordable Care Act, also known as Obamacare. The law is meant to provide incentives for people to secure health benefits. One controversial section of the bill is the individual mandate, which imposes a penalty on persons who do not purchase health insurance. However, the Supreme Court has ruled that the mandate is constitutional under Congress''s designated taxing power. ', 'Healthcare Reform', 100, 'healthcare reform, obamacare', 'healthcare-reform', '', 0, 0, ''),
(142, 'photo', 'http://images.onlineuniversity.net.s3.amazonaws.com/new-student-loan-deal.jpg', 1, 'In 2010, Obama signed into law the Health Care and Education Reconciliation Act of 2010, which included a number of loan reforms for students. Its provisions include: an increase in Pell Grant awards, loan forgiveness after 20 years (previously 25), a cap on repayments at 10% (previously 15%), and increasing funding.', 'Education Reform', 91, 'education, student loans', 'education-reform', '', 0, 0, ''),
(143, 'photo', 'http://sociable.co/wp-content/uploads/2011/12/SOPA-business-infographic-488x2761.png', 1, 'The Stop Online Piracy Act (SOPA) is a bill that expands the rights of law enforcement to fight illegal sharing of copyrighted materials. ', 'SOPA', 88, 'sopa', 'sopa', '', 0, 0, ''),
(144, 'secondary', 'http://www.ocsmallclaims.com/Downloads/FactSheets/Appeal.doc', 1, 'How to File a Small Claims Appeal', 'How to File a Small Claims Appeal', 0, 'small claims', 'how-to-file-a-small-claims-appeal', '', 0, 0, 'TEST'),
(145, 'news', 'http://www.huffingtonpost.com/2012/06/28/obamacare-women-supreme-court-contraception-pregnancy_n_1634480.html', 1, 'WASHINGTON -- Although the requirement that contraception be covered by employers'' health care plans was not an issue addressed by the Supreme Court on Thursday, the measure has become one of the most controversial aspects of the Affordable Care Act.', 'Obamacare Ruling Is ''Major Victory'' For Women', 83, 'healthcare reform, women, obamacare', 'obamacare-ruling-is-major-victory-for-women', '', 0, 0, ''),
(146, 'secondary', 'http://inventors.about.com/od/trademarks/a/register.htm', 2, 'You are not required to register a trademark and can establish rights over that mark based on legitimate use. However, The benefits of having a registered trademark as compared to a common law trademark include: constructive notice nationwide of the trademark owner''s claim, additional evidence of the ownership of the trademark, jurisdiction of federal courts may be invoked, registration can be used as a basis for obtaining registration in other countries.', 'Why You Should Register a Trademark', 84, 'ip, trademark', 'why-you-should-register-a-trademark', '', 0, 0, ''),
(147, 'secondary', 'https://www.google.com/?tbm=pts&hl=en', 2, 'With Google Patents, you can search the full text of the U.S. patent corpus. The search engine covers the entire collection of issued patents and millions of patent application made available by the USPTO, from patents issued in the 1790s through the present.', 'Search for Patent', 82, 'ip, patent, name search', 'search-for-patent', '', 0, 0, ''),
(148, 'primary', 'http://walkercorporatelaw.com/entrepreneurship/issuing-stock-options-ten-tips-for-entrepreneurs/', 2, 'Stock options should be issued ASAP. This is so that employees can profit from any increase in revenue. A company should establish a realistic vesting schedule. This will incentivize the employees to remain w/the company to help grow the business.', 'Issuing Stock Options: Ten Tips For Entrepreneurs', 50, 'tax, stocks, options', 'issuing-stock-options-ten-tips-for-entrepreneurs', '', 0, 0, '');

-- --------------------------------------------------------

--
-- Table structure for table `tags`
--

CREATE TABLE IF NOT EXISTS `tags` (
  `id` int(10) NOT NULL auto_increment,
  `tagname` varchar(30) collate latin1_general_ci NOT NULL,
  `parent` int(10) NOT NULL,
  `summary` varchar(1000) collate latin1_general_ci NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `tagname` (`tagname`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=6 ;

--
-- Dumping data for table `tags`
--

INSERT INTO `tags` (`id`, `tagname`, `parent`, `summary`) VALUES
(1, 'Gay Marriage', 0, '0'),
(2, 'DOMA', 1, 'The Defense of Marriage Act (DOMA) is a federal law that defines marriage as the legal union of one man and one woman. However, DOMA has been challenged because it may violate the principle of Federalism. In Massachusetts v. United States Department of Health and Human Services, the First Circuit ruled that DOMA was unconstitutional because the Federal Government does not have the power to define marriage. It is likely that the SCOTUS will hear the case sometime after the 2012 election to ultimately decide DOMA''s fate.  '),
(3, 'Federalism', 1, ' DOMA may be invalidated under the principle of Federalism, which was established by the Tenth Amendment. Federalism is a system of government where some issues are exclusively handled by the States, and others by the Federal Government. Traditionally, the power to define marriage has been granted to the States. Therefore, DOMA might be unconstitutional because the Federal Government did not have the right to define marriage in the first place.  '),
(4, 'California Gay Marriage', 1, 'California formerly granted marriage licenses to same-sex couples beginning on June 16, 2008. However, due to the passage of Proposition 8, it discontinued to do so on November 5, 2008. Prop 8 was a ballot that passed in the November 2008 election which provided an amendment to the California Constitution that limited marriages to those between one man and one woman, '),
(5, 'Same Sex Marriage', 1, 'Marriage is defined as the union of one man and one woman in at least 42 states. Currently, 31 states have added amendments banning same-sex unions to their constitutions. There are currently eight states that recognize or will soon recognize same-sex marriages, and a total of six (plus the District of Columbia) that recognize some form of same-sex civil unions or domestic partnerships.');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
